"""add username and full name to user

Revision ID: 580a99e375c8
Revises: bd116515db63
Create Date: 2026-03-04 02:53:08.467633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580a99e375c8'
down_revision: Union[str, Sequence[str], None] = 'bd116515db63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('fullName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashedPassword', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'hashedPassword')
    op.drop_column('users', 'fullName')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
