"""create cafes table

Revision ID: 641d8dd6c45d
Revises: f711cce308d2
Create Date: 2026-03-03 00:58:46.217530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641d8dd6c45d'
down_revision: Union[str, Sequence[str], None] = 'f711cce308d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafes',
    sa.Column('cafeId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('mapsId', sa.String(), nullable=False),
    sa.Column('mapsUrl', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cafeId')
    )
    op.create_index(op.f('ix_cafes_cafeId'), 'cafes', ['cafeId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cafes_cafeId'), table_name='cafes')
    op.drop_table('cafes')
    # ### end Alembic commands ###
