"""relate cafe to activity

Revision ID: 888a4679ac2c
Revises: 641d8dd6c45d
Create Date: 2026-03-03 01:33:01.892512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888a4679ac2c'
down_revision: Union[str, Sequence[str], None] = '641d8dd6c45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('cafeId', sa.Integer(), nullable=False))
    op.add_column('activities', sa.Column('review', sa.String(), nullable=True))
    op.create_foreign_key(None, 'activities', 'cafes', ['cafeId'], ['cafeId'])
    op.drop_column('activities', 'placeId')
    op.drop_column('activities', 'placeAddress')
    op.drop_column('activities', 'placeName')
    op.drop_column('activities', 'hasReview')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('hasReview', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('placeName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('placeAddress', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('placeId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'review')
    op.drop_column('activities', 'cafeId')
    # ### end Alembic commands ###
