"""relate user and activity

Revision ID: b431b7e1ed95
Revises: 580a99e375c8
Create Date: 2026-03-04 13:31:48.451441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b431b7e1ed95'
down_revision: Union[str, Sequence[str], None] = '580a99e375c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('userId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'activities', 'users', ['userId'], ['userId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'userId')
    # ### end Alembic commands ###
