"""add slug to cafe

Revision ID: c342a816ae6d
Revises: 7f5d26c6ec59
Create Date: 2026-03-06 12:32:45.427368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c342a816ae6d'
down_revision: Union[str, Sequence[str], None] = '7f5d26c6ec59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_cafes_slug'), 'cafes', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cafes_slug'), table_name='cafes')
    op.drop_column('cafes', 'slug')
    # ### end Alembic commands ###
