"""create activities table

Revision ID: f711cce308d2
Revises: 
Create Date: 2026-03-02 11:44:20.570346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f711cce308d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('placeId', sa.String(), nullable=False),
    sa.Column('placeName', sa.String(), nullable=False),
    sa.Column('placeAddress', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('hasReview', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('activityId')
    )
    op.create_index(op.f('ix_activities_activityId'), 'activities', ['activityId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_activityId'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
